const CashData = [
  {
    _id: "664db348373932f6a08928db",
    title: "What is a Pricing Strategy?",
    imgurl:
      "https://media.licdn.com/dms/image/D4D12AQGmdsV2X-5tgA/article-cover_image-shrink_423_752/0/1714061025222?e=1721865600&v=beta&t=y9WdIMtf9kxkTlFA1-99EBtQzhwGNElMzoQz9n1R3d4",
    description:
      "A pricing strategy is how businesses decide on product prices to boost sales and ensure profits. It’s also about where the brand stands among consumers",
    service: "1",
    section: "1",
    body: "A pricing strategy is how businesses decide on product prices to boost sales and ensure profits. It’s also about where the brand stands among consumers. The goal is to find appealing and competitive prices in the market. This strategy is vital for businesses and needs careful planning.\nThe Role of Pricing Strategy\nTo meet customer needs, businesses must consider two things: what customers want and what they can afford. Price determines the target customer group. A good pricing strategy boosts revenue by targeting the right customers and making them satisfied with the prices, not just offering the lowest price. Timing matters too, so pricing should fit the product’s life cycle and brand positioning.\nCommon Mistakes in Pricing Strategy\nBusinesses often make these mistakes, which can lead to revenue loss:\nCompeting solely on price, which can hurt revenue in the long run.\nLack of a clear pricing strategy, frustrating customers.\nFocusing too much on competitors’ prices, risking losing their own positioning.\nSteps to the Right Pricing Strategy\nAnalyze production costs, including operating costs, salaries, and marketing expenses.\nAssess the market potential to forecast product consumption and its impact on costs and prices.\nDetermine the ideal price range based on available information.\nPopular Pricing Strategies\n1. Skimming Strategy: Ideal for unique products, setting high prices initially to maximize profits, often used in tech or trendy products, though it can alienate consumers.\n2. Market Penetration Pricing Strategy: Lower prices than competitors to attract initial users, often used in fast-moving consumer goods (FMCG) markets.\n3. Fluctuating Pricing Strategy: Prices change based on algorithms, personalized to each customer, popular in recent years.\n4. Cost-Based Pricing Strategy: Simplest strategy, adding desired profit to costs, but needs customer research.\n5. Competitor-Based Pricing: Setting prices based on competitors’ prices, suitable for small businesses, but may not fit the business well.",
    createdAt: "2024-05-22T08:56:40.793Z",
    updatedAt: "2024-05-22T08:56:40.793Z",
    __v: 0,
  },
  {
    _id: "664db351373932f6a08928dd",
    title: "What is the Butterfly Effect: Simple Explanation and Examples",
    imgurl:
      "https://media.licdn.com/dms/image/D4D12AQGlLfH9GjAx9w/article-cover_image-shrink_423_752/0/1714061121713?e=1721865600&v=beta&t=eOTYOxTPku5wysUXbF2eHFRIC_WDOdncUiMniryMcNQ",
    description: "",
    service: "2",
    section: "2",
    body: "What is the Butterfly Effect?\nThe Butterfly Effect is a concept from chaos theory. It suggests that even small actions can have big consequences. It’s like a tiny butterfly flapping its wings, which could eventually cause a tornado on the other side of the world.\nHow Does it Work?\nImagine you decide to water a plant one day. Seems simple, right? But think about it. By watering the plant, you’re changing the environment around it. The soil gets moist, which helps the plant grow. As the plant grows, it provides oxygen, affecting the air around it. Birds might come to perch on it, spreading seeds to new places. And on and on it goes.\nExamples of the Butterfly Effect:\nTraffic Jams: You’re driving and you decide to take a different route. That tiny decision might lead to you avoiding a big traffic jam.\nSocial Media: You share a post, and it gets shared by your friends, then by their friends, and so on. Soon, it’s viral!\nWeather Patterns: A butterfly flaps its wings in Brazil, and weeks later, it’s part of the chain reaction that leads to a storm in the Atlantic.\nWhy Does it Matter?\nUnderstanding the Butterfly Effect reminds us that our actions matter. It shows how interconnected everything is. So even small acts of kindness or responsibility can ripple out and make a big difference.\nIn Conclusion\nThe Butterfly Effect teaches us to be mindful of our actions. It shows us that the world is a complex web of connections, where even the smallest change can cause a big impact. So next time you’re wondering if what you do matters, remember the Butterfly Effect.",
    createdAt: "2024-05-22T08:56:49.785Z",
    updatedAt: "2024-05-22T08:56:49.785Z",
    __v: 0,
  },
  {
    _id: "664db351373932f6a08928dd",
    title: "What is the Butterfly Effect: Simple Explanation and Examples",
    imgurl:
      "https://media.licdn.com/dms/image/D4D12AQGlLfH9GjAx9w/article-cover_image-shrink_423_752/0/1714061121713?e=1721865600&v=beta&t=eOTYOxTPku5wysUXbF2eHFRIC_WDOdncUiMniryMcNQ",
    description: "",
    service: "2",
    section: "2",
    body: "What is the Butterfly Effect?\nThe Butterfly Effect is a concept from chaos theory. It suggests that even small actions can have big consequences. It’s like a tiny butterfly flapping its wings, which could eventually cause a tornado on the other side of the world.\nHow Does it Work?\nImagine you decide to water a plant one day. Seems simple, right? But think about it. By watering the plant, you’re changing the environment around it. The soil gets moist, which helps the plant grow. As the plant grows, it provides oxygen, affecting the air around it. Birds might come to perch on it, spreading seeds to new places. And on and on it goes.\nExamples of the Butterfly Effect:\nTraffic Jams: You’re driving and you decide to take a different route. That tiny decision might lead to you avoiding a big traffic jam.\nSocial Media: You share a post, and it gets shared by your friends, then by their friends, and so on. Soon, it’s viral!\nWeather Patterns: A butterfly flaps its wings in Brazil, and weeks later, it’s part of the chain reaction that leads to a storm in the Atlantic.\nWhy Does it Matter?\nUnderstanding the Butterfly Effect reminds us that our actions matter. It shows how interconnected everything is. So even small acts of kindness or responsibility can ripple out and make a big difference.\nIn Conclusion\nThe Butterfly Effect teaches us to be mindful of our actions. It shows us that the world is a complex web of connections, where even the smallest change can cause a big impact. So next time you’re wondering if what you do matters, remember the Butterfly Effect.",
    createdAt: "2024-05-22T08:56:49.785Z",
    updatedAt: "2024-05-22T08:56:49.785Z",
    __v: 0,
  },
  {
    _id: "664db351373932f6a08928dd",
    title: "What is the Butterfly Effect: Simple Explanation and Examples",
    imgurl:
      "https://media.licdn.com/dms/image/D4D12AQGlLfH9GjAx9w/article-cover_image-shrink_423_752/0/1714061121713?e=1721865600&v=beta&t=eOTYOxTPku5wysUXbF2eHFRIC_WDOdncUiMniryMcNQ",
    description: "",
    service: "2",
    section: "2",
    body: "What is the Butterfly Effect?\nThe Butterfly Effect is a concept from chaos theory. It suggests that even small actions can have big consequences. It’s like a tiny butterfly flapping its wings, which could eventually cause a tornado on the other side of the world.\nHow Does it Work?\nImagine you decide to water a plant one day. Seems simple, right? But think about it. By watering the plant, you’re changing the environment around it. The soil gets moist, which helps the plant grow. As the plant grows, it provides oxygen, affecting the air around it. Birds might come to perch on it, spreading seeds to new places. And on and on it goes.\nExamples of the Butterfly Effect:\nTraffic Jams: You’re driving and you decide to take a different route. That tiny decision might lead to you avoiding a big traffic jam.\nSocial Media: You share a post, and it gets shared by your friends, then by their friends, and so on. Soon, it’s viral!\nWeather Patterns: A butterfly flaps its wings in Brazil, and weeks later, it’s part of the chain reaction that leads to a storm in the Atlantic.\nWhy Does it Matter?\nUnderstanding the Butterfly Effect reminds us that our actions matter. It shows how interconnected everything is. So even small acts of kindness or responsibility can ripple out and make a big difference.\nIn Conclusion\nThe Butterfly Effect teaches us to be mindful of our actions. It shows us that the world is a complex web of connections, where even the smallest change can cause a big impact. So next time you’re wondering if what you do matters, remember the Butterfly Effect.",
    createdAt: "2024-05-22T08:56:49.785Z",
    updatedAt: "2024-05-22T08:56:49.785Z",
    __v: 0,
  },
  {
    _id: "664db351373932f6a08928dd",
    title: "What is the Butterfly Effect: Simple Explanation and Examples",
    imgurl:
      "https://media.licdn.com/dms/image/D4D12AQGlLfH9GjAx9w/article-cover_image-shrink_423_752/0/1714061121713?e=1721865600&v=beta&t=eOTYOxTPku5wysUXbF2eHFRIC_WDOdncUiMniryMcNQ",
    description: "",
    service: "2",
    section: "2",
    body: "What is the Butterfly Effect?\nThe Butterfly Effect is a concept from chaos theory. It suggests that even small actions can have big consequences. It’s like a tiny butterfly flapping its wings, which could eventually cause a tornado on the other side of the world.\nHow Does it Work?\nImagine you decide to water a plant one day. Seems simple, right? But think about it. By watering the plant, you’re changing the environment around it. The soil gets moist, which helps the plant grow. As the plant grows, it provides oxygen, affecting the air around it. Birds might come to perch on it, spreading seeds to new places. And on and on it goes.\nExamples of the Butterfly Effect:\nTraffic Jams: You’re driving and you decide to take a different route. That tiny decision might lead to you avoiding a big traffic jam.\nSocial Media: You share a post, and it gets shared by your friends, then by their friends, and so on. Soon, it’s viral!\nWeather Patterns: A butterfly flaps its wings in Brazil, and weeks later, it’s part of the chain reaction that leads to a storm in the Atlantic.\nWhy Does it Matter?\nUnderstanding the Butterfly Effect reminds us that our actions matter. It shows how interconnected everything is. So even small acts of kindness or responsibility can ripple out and make a big difference.\nIn Conclusion\nThe Butterfly Effect teaches us to be mindful of our actions. It shows us that the world is a complex web of connections, where even the smallest change can cause a big impact. So next time you’re wondering if what you do matters, remember the Butterfly Effect.",
    createdAt: "2024-05-22T08:56:49.785Z",
    updatedAt: "2024-05-22T08:56:49.785Z",
    __v: 0,
  },
  {
    _id: "664db351373932f6a08928dd",
    title: "What is the Butterfly Effect: Simple Explanation and Examples",
    imgurl:
      "https://media.licdn.com/dms/image/D4D12AQGlLfH9GjAx9w/article-cover_image-shrink_423_752/0/1714061121713?e=1721865600&v=beta&t=eOTYOxTPku5wysUXbF2eHFRIC_WDOdncUiMniryMcNQ",
    description: "",
    service: "2",
    section: "3",
    body: "What is the Butterfly Effect?\nThe Butterfly Effect is a concept from chaos theory. It suggests that even small actions can have big consequences. It’s like a tiny butterfly flapping its wings, which could eventually cause a tornado on the other side of the world.\nHow Does it Work?\nImagine you decide to water a plant one day. Seems simple, right? But think about it. By watering the plant, you’re changing the environment around it. The soil gets moist, which helps the plant grow. As the plant grows, it provides oxygen, affecting the air around it. Birds might come to perch on it, spreading seeds to new places. And on and on it goes.\nExamples of the Butterfly Effect:\nTraffic Jams: You’re driving and you decide to take a different route. That tiny decision might lead to you avoiding a big traffic jam.\nSocial Media: You share a post, and it gets shared by your friends, then by their friends, and so on. Soon, it’s viral!\nWeather Patterns: A butterfly flaps its wings in Brazil, and weeks later, it’s part of the chain reaction that leads to a storm in the Atlantic.\nWhy Does it Matter?\nUnderstanding the Butterfly Effect reminds us that our actions matter. It shows how interconnected everything is. So even small acts of kindness or responsibility can ripple out and make a big difference.\nIn Conclusion\nThe Butterfly Effect teaches us to be mindful of our actions. It shows us that the world is a complex web of connections, where even the smallest change can cause a big impact. So next time you’re wondering if what you do matters, remember the Butterfly Effect.",
    createdAt: "2024-05-22T08:56:49.785Z",
    updatedAt: "2024-05-22T08:56:49.785Z",
    __v: 0,
  },
  {
    _id: "664db351373932f6a08928dd",
    title: "What is the Butterfly Effect: Simple Explanation and Examples",
    imgurl:
      "https://media.licdn.com/dms/image/D4D12AQGlLfH9GjAx9w/article-cover_image-shrink_423_752/0/1714061121713?e=1721865600&v=beta&t=eOTYOxTPku5wysUXbF2eHFRIC_WDOdncUiMniryMcNQ",
    description: "",
    service: "2",
    section: "3",
    body: "What is the Butterfly Effect?\nThe Butterfly Effect is a concept from chaos theory. It suggests that even small actions can have big consequences. It’s like a tiny butterfly flapping its wings, which could eventually cause a tornado on the other side of the world.\nHow Does it Work?\nImagine you decide to water a plant one day. Seems simple, right? But think about it. By watering the plant, you’re changing the environment around it. The soil gets moist, which helps the plant grow. As the plant grows, it provides oxygen, affecting the air around it. Birds might come to perch on it, spreading seeds to new places. And on and on it goes.\nExamples of the Butterfly Effect:\nTraffic Jams: You’re driving and you decide to take a different route. That tiny decision might lead to you avoiding a big traffic jam.\nSocial Media: You share a post, and it gets shared by your friends, then by their friends, and so on. Soon, it’s viral!\nWeather Patterns: A butterfly flaps its wings in Brazil, and weeks later, it’s part of the chain reaction that leads to a storm in the Atlantic.\nWhy Does it Matter?\nUnderstanding the Butterfly Effect reminds us that our actions matter. It shows how interconnected everything is. So even small acts of kindness or responsibility can ripple out and make a big difference.\nIn Conclusion\nThe Butterfly Effect teaches us to be mindful of our actions. It shows us that the world is a complex web of connections, where even the smallest change can cause a big impact. So next time you’re wondering if what you do matters, remember the Butterfly Effect.",
    createdAt: "2024-05-22T08:56:49.785Z",
    updatedAt: "2024-05-22T08:56:49.785Z",
    __v: 0,
  },
  {
    _id: "664db351373932f6a08928dd",
    title: "What is the Butterfly Effect: Simple Explanation and Examples",
    imgurl:
      "https://media.licdn.com/dms/image/D4D12AQGlLfH9GjAx9w/article-cover_image-shrink_423_752/0/1714061121713?e=1721865600&v=beta&t=eOTYOxTPku5wysUXbF2eHFRIC_WDOdncUiMniryMcNQ",
    description: "",
    service: "2",
    section: "3",
    body: "What is the Butterfly Effect?\nThe Butterfly Effect is a concept from chaos theory. It suggests that even small actions can have big consequences. It’s like a tiny butterfly flapping its wings, which could eventually cause a tornado on the other side of the world.\nHow Does it Work?\nImagine you decide to water a plant one day. Seems simple, right? But think about it. By watering the plant, you’re changing the environment around it. The soil gets moist, which helps the plant grow. As the plant grows, it provides oxygen, affecting the air around it. Birds might come to perch on it, spreading seeds to new places. And on and on it goes.\nExamples of the Butterfly Effect:\nTraffic Jams: You’re driving and you decide to take a different route. That tiny decision might lead to you avoiding a big traffic jam.\nSocial Media: You share a post, and it gets shared by your friends, then by their friends, and so on. Soon, it’s viral!\nWeather Patterns: A butterfly flaps its wings in Brazil, and weeks later, it’s part of the chain reaction that leads to a storm in the Atlantic.\nWhy Does it Matter?\nUnderstanding the Butterfly Effect reminds us that our actions matter. It shows how interconnected everything is. So even small acts of kindness or responsibility can ripple out and make a big difference.\nIn Conclusion\nThe Butterfly Effect teaches us to be mindful of our actions. It shows us that the world is a complex web of connections, where even the smallest change can cause a big impact. So next time you’re wondering if what you do matters, remember the Butterfly Effect.",
    createdAt: "2024-05-22T08:56:49.785Z",
    updatedAt: "2024-05-22T08:56:49.785Z",
    __v: 0,
  },
  {
    _id: "664db351373932f6a08928dd",
    title: "What is the Butterfly Effect: Simple Explanation and Examples",
    imgurl:
      "https://media.licdn.com/dms/image/D4D12AQGlLfH9GjAx9w/article-cover_image-shrink_423_752/0/1714061121713?e=1721865600&v=beta&t=eOTYOxTPku5wysUXbF2eHFRIC_WDOdncUiMniryMcNQ",
    description: "",
    service: "2",
    section: "3",
    body: "What is the Butterfly Effect?\nThe Butterfly Effect is a concept from chaos theory. It suggests that even small actions can have big consequences. It’s like a tiny butterfly flapping its wings, which could eventually cause a tornado on the other side of the world.\nHow Does it Work?\nImagine you decide to water a plant one day. Seems simple, right? But think about it. By watering the plant, you’re changing the environment around it. The soil gets moist, which helps the plant grow. As the plant grows, it provides oxygen, affecting the air around it. Birds might come to perch on it, spreading seeds to new places. And on and on it goes.\nExamples of the Butterfly Effect:\nTraffic Jams: You’re driving and you decide to take a different route. That tiny decision might lead to you avoiding a big traffic jam.\nSocial Media: You share a post, and it gets shared by your friends, then by their friends, and so on. Soon, it’s viral!\nWeather Patterns: A butterfly flaps its wings in Brazil, and weeks later, it’s part of the chain reaction that leads to a storm in the Atlantic.\nWhy Does it Matter?\nUnderstanding the Butterfly Effect reminds us that our actions matter. It shows how interconnected everything is. So even small acts of kindness or responsibility can ripple out and make a big difference.\nIn Conclusion\nThe Butterfly Effect teaches us to be mindful of our actions. It shows us that the world is a complex web of connections, where even the smallest change can cause a big impact. So next time you’re wondering if what you do matters, remember the Butterfly Effect.",
    createdAt: "2024-05-22T08:56:49.785Z",
    updatedAt: "2024-05-22T08:56:49.785Z",
    __v: 0,
  },
  {
    _id: "664db351373932f6a08928dd",
    title: "What is the Butterfly Effect: Simple Explanation and Examples",
    imgurl:
      "https://media.licdn.com/dms/image/D4D12AQGlLfH9GjAx9w/article-cover_image-shrink_423_752/0/1714061121713?e=1721865600&v=beta&t=eOTYOxTPku5wysUXbF2eHFRIC_WDOdncUiMniryMcNQ",
    description: "",
    service: "2",
    section: "4",
    body: "What is the Butterfly Effect?\nThe Butterfly Effect is a concept from chaos theory. It suggests that even small actions can have big consequences. It’s like a tiny butterfly flapping its wings, which could eventually cause a tornado on the other side of the world.\nHow Does it Work?\nImagine you decide to water a plant one day. Seems simple, right? But think about it. By watering the plant, you’re changing the environment around it. The soil gets moist, which helps the plant grow. As the plant grows, it provides oxygen, affecting the air around it. Birds might come to perch on it, spreading seeds to new places. And on and on it goes.\nExamples of the Butterfly Effect:\nTraffic Jams: You’re driving and you decide to take a different route. That tiny decision might lead to you avoiding a big traffic jam.\nSocial Media: You share a post, and it gets shared by your friends, then by their friends, and so on. Soon, it’s viral!\nWeather Patterns: A butterfly flaps its wings in Brazil, and weeks later, it’s part of the chain reaction that leads to a storm in the Atlantic.\nWhy Does it Matter?\nUnderstanding the Butterfly Effect reminds us that our actions matter. It shows how interconnected everything is. So even small acts of kindness or responsibility can ripple out and make a big difference.\nIn Conclusion\nThe Butterfly Effect teaches us to be mindful of our actions. It shows us that the world is a complex web of connections, where even the smallest change can cause a big impact. So next time you’re wondering if what you do matters, remember the Butterfly Effect.",
    createdAt: "2024-05-22T08:56:49.785Z",
    updatedAt: "2024-05-22T08:56:49.785Z",
    __v: 0,
  },
  {
    _id: "664db351373932f6a08928dd",
    title: "What is the Butterfly Effect: Simple Explanation and Examples",
    imgurl:
      "https://media.licdn.com/dms/image/D4D12AQGlLfH9GjAx9w/article-cover_image-shrink_423_752/0/1714061121713?e=1721865600&v=beta&t=eOTYOxTPku5wysUXbF2eHFRIC_WDOdncUiMniryMcNQ",
    description: "",
    service: "2",
    section: "4",
    body: "What is the Butterfly Effect?\nThe Butterfly Effect is a concept from chaos theory. It suggests that even small actions can have big consequences. It’s like a tiny butterfly flapping its wings, which could eventually cause a tornado on the other side of the world.\nHow Does it Work?\nImagine you decide to water a plant one day. Seems simple, right? But think about it. By watering the plant, you’re changing the environment around it. The soil gets moist, which helps the plant grow. As the plant grows, it provides oxygen, affecting the air around it. Birds might come to perch on it, spreading seeds to new places. And on and on it goes.\nExamples of the Butterfly Effect:\nTraffic Jams: You’re driving and you decide to take a different route. That tiny decision might lead to you avoiding a big traffic jam.\nSocial Media: You share a post, and it gets shared by your friends, then by their friends, and so on. Soon, it’s viral!\nWeather Patterns: A butterfly flaps its wings in Brazil, and weeks later, it’s part of the chain reaction that leads to a storm in the Atlantic.\nWhy Does it Matter?\nUnderstanding the Butterfly Effect reminds us that our actions matter. It shows how interconnected everything is. So even small acts of kindness or responsibility can ripple out and make a big difference.\nIn Conclusion\nThe Butterfly Effect teaches us to be mindful of our actions. It shows us that the world is a complex web of connections, where even the smallest change can cause a big impact. So next time you’re wondering if what you do matters, remember the Butterfly Effect.",
    createdAt: "2024-05-22T08:56:49.785Z",
    updatedAt: "2024-05-22T08:56:49.785Z",
    __v: 0,
  },
  {
    _id: "664db351373932f6a08928dd",
    title: "What is the Butterfly Effect: Simple Explanation and Examples",
    imgurl:
      "https://media.licdn.com/dms/image/D4D12AQGlLfH9GjAx9w/article-cover_image-shrink_423_752/0/1714061121713?e=1721865600&v=beta&t=eOTYOxTPku5wysUXbF2eHFRIC_WDOdncUiMniryMcNQ",
    description: "",
    service: "2",
    section: "4",
    body: "What is the Butterfly Effect?\nThe Butterfly Effect is a concept from chaos theory. It suggests that even small actions can have big consequences. It’s like a tiny butterfly flapping its wings, which could eventually cause a tornado on the other side of the world.\nHow Does it Work?\nImagine you decide to water a plant one day. Seems simple, right? But think about it. By watering the plant, you’re changing the environment around it. The soil gets moist, which helps the plant grow. As the plant grows, it provides oxygen, affecting the air around it. Birds might come to perch on it, spreading seeds to new places. And on and on it goes.\nExamples of the Butterfly Effect:\nTraffic Jams: You’re driving and you decide to take a different route. That tiny decision might lead to you avoiding a big traffic jam.\nSocial Media: You share a post, and it gets shared by your friends, then by their friends, and so on. Soon, it’s viral!\nWeather Patterns: A butterfly flaps its wings in Brazil, and weeks later, it’s part of the chain reaction that leads to a storm in the Atlantic.\nWhy Does it Matter?\nUnderstanding the Butterfly Effect reminds us that our actions matter. It shows how interconnected everything is. So even small acts of kindness or responsibility can ripple out and make a big difference.\nIn Conclusion\nThe Butterfly Effect teaches us to be mindful of our actions. It shows us that the world is a complex web of connections, where even the smallest change can cause a big impact. So next time you’re wondering if what you do matters, remember the Butterfly Effect.",
    createdAt: "2024-05-22T08:56:49.785Z",
    updatedAt: "2024-05-22T08:56:49.785Z",
    __v: 0,
  },
  {
    _id: "664db351373932f6a08928dd",
    title: "What is the Butterfly Effect: Simple Explanation and Examples",
    imgurl:
      "https://media.licdn.com/dms/image/D4D12AQGlLfH9GjAx9w/article-cover_image-shrink_423_752/0/1714061121713?e=1721865600&v=beta&t=eOTYOxTPku5wysUXbF2eHFRIC_WDOdncUiMniryMcNQ",
    description: "",
    service: "2",
    section: "4",
    body: "What is the Butterfly Effect?\nThe Butterfly Effect is a concept from chaos theory. It suggests that even small actions can have big consequences. It’s like a tiny butterfly flapping its wings, which could eventually cause a tornado on the other side of the world.\nHow Does it Work?\nImagine you decide to water a plant one day. Seems simple, right? But think about it. By watering the plant, you’re changing the environment around it. The soil gets moist, which helps the plant grow. As the plant grows, it provides oxygen, affecting the air around it. Birds might come to perch on it, spreading seeds to new places. And on and on it goes.\nExamples of the Butterfly Effect:\nTraffic Jams: You’re driving and you decide to take a different route. That tiny decision might lead to you avoiding a big traffic jam.\nSocial Media: You share a post, and it gets shared by your friends, then by their friends, and so on. Soon, it’s viral!\nWeather Patterns: A butterfly flaps its wings in Brazil, and weeks later, it’s part of the chain reaction that leads to a storm in the Atlantic.\nWhy Does it Matter?\nUnderstanding the Butterfly Effect reminds us that our actions matter. It shows how interconnected everything is. So even small acts of kindness or responsibility can ripple out and make a big difference.\nIn Conclusion\nThe Butterfly Effect teaches us to be mindful of our actions. It shows us that the world is a complex web of connections, where even the smallest change can cause a big impact. So next time you’re wondering if what you do matters, remember the Butterfly Effect.",
    createdAt: "2024-05-22T08:56:49.785Z",
    updatedAt: "2024-05-22T08:56:49.785Z",
    __v: 0,
  },
  {
    _id: "664db351373932f6a08928dd",
    title: "What is the Butterfly Effect: Simple Explanation and Examples",
    imgurl:
      "https://media.licdn.com/dms/image/D4D12AQGlLfH9GjAx9w/article-cover_image-shrink_423_752/0/1714061121713?e=1721865600&v=beta&t=eOTYOxTPku5wysUXbF2eHFRIC_WDOdncUiMniryMcNQ",
    description: "",
    service: "2",
    section: "8",
    body: "What is the Butterfly Effect?\nThe Butterfly Effect is a concept from chaos theory. It suggests that even small actions can have big consequences. It’s like a tiny butterfly flapping its wings, which could eventually cause a tornado on the other side of the world.\nHow Does it Work?\nImagine you decide to water a plant one day. Seems simple, right? But think about it. By watering the plant, you’re changing the environment around it. The soil gets moist, which helps the plant grow. As the plant grows, it provides oxygen, affecting the air around it. Birds might come to perch on it, spreading seeds to new places. And on and on it goes.\nExamples of the Butterfly Effect:\nTraffic Jams: You’re driving and you decide to take a different route. That tiny decision might lead to you avoiding a big traffic jam.\nSocial Media: You share a post, and it gets shared by your friends, then by their friends, and so on. Soon, it’s viral!\nWeather Patterns: A butterfly flaps its wings in Brazil, and weeks later, it’s part of the chain reaction that leads to a storm in the Atlantic.\nWhy Does it Matter?\nUnderstanding the Butterfly Effect reminds us that our actions matter. It shows how interconnected everything is. So even small acts of kindness or responsibility can ripple out and make a big difference.\nIn Conclusion\nThe Butterfly Effect teaches us to be mindful of our actions. It shows us that the world is a complex web of connections, where even the smallest change can cause a big impact. So next time you’re wondering if what you do matters, remember the Butterfly Effect.",
    createdAt: "2024-05-22T08:56:49.785Z",
    updatedAt: "2024-05-22T08:56:49.785Z",
    __v: 0,
  },
  {
    _id: "664db351373932f6a08928dd",
    title: "What is the Butterfly Effect: Simple Explanation and Examples",
    imgurl:
      "https://media.licdn.com/dms/image/D4D12AQGlLfH9GjAx9w/article-cover_image-shrink_423_752/0/1714061121713?e=1721865600&v=beta&t=eOTYOxTPku5wysUXbF2eHFRIC_WDOdncUiMniryMcNQ",
    description: "",
    service: "2",
    section: "8",
    body: "What is the Butterfly Effect?\nThe Butterfly Effect is a concept from chaos theory. It suggests that even small actions can have big consequences. It’s like a tiny butterfly flapping its wings, which could eventually cause a tornado on the other side of the world.\nHow Does it Work?\nImagine you decide to water a plant one day. Seems simple, right? But think about it. By watering the plant, you’re changing the environment around it. The soil gets moist, which helps the plant grow. As the plant grows, it provides oxygen, affecting the air around it. Birds might come to perch on it, spreading seeds to new places. And on and on it goes.\nExamples of the Butterfly Effect:\nTraffic Jams: You’re driving and you decide to take a different route. That tiny decision might lead to you avoiding a big traffic jam.\nSocial Media: You share a post, and it gets shared by your friends, then by their friends, and so on. Soon, it’s viral!\nWeather Patterns: A butterfly flaps its wings in Brazil, and weeks later, it’s part of the chain reaction that leads to a storm in the Atlantic.\nWhy Does it Matter?\nUnderstanding the Butterfly Effect reminds us that our actions matter. It shows how interconnected everything is. So even small acts of kindness or responsibility can ripple out and make a big difference.\nIn Conclusion\nThe Butterfly Effect teaches us to be mindful of our actions. It shows us that the world is a complex web of connections, where even the smallest change can cause a big impact. So next time you’re wondering if what you do matters, remember the Butterfly Effect.",
    createdAt: "2024-05-22T08:56:49.785Z",
    updatedAt: "2024-05-22T08:56:49.785Z",
    __v: 0,
  },
  {
    _id: "664db351373932f6a08928dd",
    title: "What is the Butterfly Effect: Simple Explanation and Examples",
    imgurl:
      "https://media.licdn.com/dms/image/D4D12AQGlLfH9GjAx9w/article-cover_image-shrink_423_752/0/1714061121713?e=1721865600&v=beta&t=eOTYOxTPku5wysUXbF2eHFRIC_WDOdncUiMniryMcNQ",
    description: "",
    service: "2",
    section: "8",
    body: "What is the Butterfly Effect?\nThe Butterfly Effect is a concept from chaos theory. It suggests that even small actions can have big consequences. It’s like a tiny butterfly flapping its wings, which could eventually cause a tornado on the other side of the world.\nHow Does it Work?\nImagine you decide to water a plant one day. Seems simple, right? But think about it. By watering the plant, you’re changing the environment around it. The soil gets moist, which helps the plant grow. As the plant grows, it provides oxygen, affecting the air around it. Birds might come to perch on it, spreading seeds to new places. And on and on it goes.\nExamples of the Butterfly Effect:\nTraffic Jams: You’re driving and you decide to take a different route. That tiny decision might lead to you avoiding a big traffic jam.\nSocial Media: You share a post, and it gets shared by your friends, then by their friends, and so on. Soon, it’s viral!\nWeather Patterns: A butterfly flaps its wings in Brazil, and weeks later, it’s part of the chain reaction that leads to a storm in the Atlantic.\nWhy Does it Matter?\nUnderstanding the Butterfly Effect reminds us that our actions matter. It shows how interconnected everything is. So even small acts of kindness or responsibility can ripple out and make a big difference.\nIn Conclusion\nThe Butterfly Effect teaches us to be mindful of our actions. It shows us that the world is a complex web of connections, where even the smallest change can cause a big impact. So next time you’re wondering if what you do matters, remember the Butterfly Effect.",
    createdAt: "2024-05-22T08:56:49.785Z",
    updatedAt: "2024-05-22T08:56:49.785Z",
    __v: 0,
  },
  {
    _id: "664db351373932f6a08928dd",
    title: "What is the Butterfly Effect: Simple Explanation and Examples",
    imgurl:
      "https://media.licdn.com/dms/image/D4D12AQGlLfH9GjAx9w/article-cover_image-shrink_423_752/0/1714061121713?e=1721865600&v=beta&t=eOTYOxTPku5wysUXbF2eHFRIC_WDOdncUiMniryMcNQ",
    description: "",
    service: "2",
    section: "8",
    body: "What is the Butterfly Effect?\nThe Butterfly Effect is a concept from chaos theory. It suggests that even small actions can have big consequences. It’s like a tiny butterfly flapping its wings, which could eventually cause a tornado on the other side of the world.\nHow Does it Work?\nImagine you decide to water a plant one day. Seems simple, right? But think about it. By watering the plant, you’re changing the environment around it. The soil gets moist, which helps the plant grow. As the plant grows, it provides oxygen, affecting the air around it. Birds might come to perch on it, spreading seeds to new places. And on and on it goes.\nExamples of the Butterfly Effect:\nTraffic Jams: You’re driving and you decide to take a different route. That tiny decision might lead to you avoiding a big traffic jam.\nSocial Media: You share a post, and it gets shared by your friends, then by their friends, and so on. Soon, it’s viral!\nWeather Patterns: A butterfly flaps its wings in Brazil, and weeks later, it’s part of the chain reaction that leads to a storm in the Atlantic.\nWhy Does it Matter?\nUnderstanding the Butterfly Effect reminds us that our actions matter. It shows how interconnected everything is. So even small acts of kindness or responsibility can ripple out and make a big difference.\nIn Conclusion\nThe Butterfly Effect teaches us to be mindful of our actions. It shows us that the world is a complex web of connections, where even the smallest change can cause a big impact. So next time you’re wondering if what you do matters, remember the Butterfly Effect.",
    createdAt: "2024-05-22T08:56:49.785Z",
    updatedAt: "2024-05-22T08:56:49.785Z",
    __v: 0,
  },
  {
    _id: "664db351373932f6a08928dd",
    title: "What is the Butterfly Effect: Simple Explanation and Examples",
    imgurl:
      "https://media.licdn.com/dms/image/D4D12AQGlLfH9GjAx9w/article-cover_image-shrink_423_752/0/1714061121713?e=1721865600&v=beta&t=eOTYOxTPku5wysUXbF2eHFRIC_WDOdncUiMniryMcNQ",
    description: "",
    service: "2",
    section: "8",
    body: "What is the Butterfly Effect?\nThe Butterfly Effect is a concept from chaos theory. It suggests that even small actions can have big consequences. It’s like a tiny butterfly flapping its wings, which could eventually cause a tornado on the other side of the world.\nHow Does it Work?\nImagine you decide to water a plant one day. Seems simple, right? But think about it. By watering the plant, you’re changing the environment around it. The soil gets moist, which helps the plant grow. As the plant grows, it provides oxygen, affecting the air around it. Birds might come to perch on it, spreading seeds to new places. And on and on it goes.\nExamples of the Butterfly Effect:\nTraffic Jams: You’re driving and you decide to take a different route. That tiny decision might lead to you avoiding a big traffic jam.\nSocial Media: You share a post, and it gets shared by your friends, then by their friends, and so on. Soon, it’s viral!\nWeather Patterns: A butterfly flaps its wings in Brazil, and weeks later, it’s part of the chain reaction that leads to a storm in the Atlantic.\nWhy Does it Matter?\nUnderstanding the Butterfly Effect reminds us that our actions matter. It shows how interconnected everything is. So even small acts of kindness or responsibility can ripple out and make a big difference.\nIn Conclusion\nThe Butterfly Effect teaches us to be mindful of our actions. It shows us that the world is a complex web of connections, where even the smallest change can cause a big impact. So next time you’re wondering if what you do matters, remember the Butterfly Effect.",
    createdAt: "2024-05-22T08:56:49.785Z",
    updatedAt: "2024-05-22T08:56:49.785Z",
    __v: 0,
  },
  {
    _id: "664db351373932f6a08928dd",
    title: "What is the Butterfly Effect: Simple Explanation and Examples",
    imgurl:
      "https://media.licdn.com/dms/image/D4D12AQGlLfH9GjAx9w/article-cover_image-shrink_423_752/0/1714061121713?e=1721865600&v=beta&t=eOTYOxTPku5wysUXbF2eHFRIC_WDOdncUiMniryMcNQ",
    description: "",
    service: "2",
    section: "8",
    body: "What is the Butterfly Effect?\nThe Butterfly Effect is a concept from chaos theory. It suggests that even small actions can have big consequences. It’s like a tiny butterfly flapping its wings, which could eventually cause a tornado on the other side of the world.\nHow Does it Work?\nImagine you decide to water a plant one day. Seems simple, right? But think about it. By watering the plant, you’re changing the environment around it. The soil gets moist, which helps the plant grow. As the plant grows, it provides oxygen, affecting the air around it. Birds might come to perch on it, spreading seeds to new places. And on and on it goes.\nExamples of the Butterfly Effect:\nTraffic Jams: You’re driving and you decide to take a different route. That tiny decision might lead to you avoiding a big traffic jam.\nSocial Media: You share a post, and it gets shared by your friends, then by their friends, and so on. Soon, it’s viral!\nWeather Patterns: A butterfly flaps its wings in Brazil, and weeks later, it’s part of the chain reaction that leads to a storm in the Atlantic.\nWhy Does it Matter?\nUnderstanding the Butterfly Effect reminds us that our actions matter. It shows how interconnected everything is. So even small acts of kindness or responsibility can ripple out and make a big difference.\nIn Conclusion\nThe Butterfly Effect teaches us to be mindful of our actions. It shows us that the world is a complex web of connections, where even the smallest change can cause a big impact. So next time you’re wondering if what you do matters, remember the Butterfly Effect.",
    createdAt: "2024-05-22T08:56:49.785Z",
    updatedAt: "2024-05-22T08:56:49.785Z",
    __v: 0,
  },
  {
    _id: "664db351373932f6a08928dd",
    title: "What is the Butterfly Effect: Simple Explanation and Examples",
    imgurl:
      "https://media.licdn.com/dms/image/D4D12AQGlLfH9GjAx9w/article-cover_image-shrink_423_752/0/1714061121713?e=1721865600&v=beta&t=eOTYOxTPku5wysUXbF2eHFRIC_WDOdncUiMniryMcNQ",
    description: "",
    service: "2",
    section: "5",
    body: "What is the Butterfly Effect?\nThe Butterfly Effect is a concept from chaos theory. It suggests that even small actions can have big consequences. It’s like a tiny butterfly flapping its wings, which could eventually cause a tornado on the other side of the world.\nHow Does it Work?\nImagine you decide to water a plant one day. Seems simple, right? But think about it. By watering the plant, you’re changing the environment around it. The soil gets moist, which helps the plant grow. As the plant grows, it provides oxygen, affecting the air around it. Birds might come to perch on it, spreading seeds to new places. And on and on it goes.\nExamples of the Butterfly Effect:\nTraffic Jams: You’re driving and you decide to take a different route. That tiny decision might lead to you avoiding a big traffic jam.\nSocial Media: You share a post, and it gets shared by your friends, then by their friends, and so on. Soon, it’s viral!\nWeather Patterns: A butterfly flaps its wings in Brazil, and weeks later, it’s part of the chain reaction that leads to a storm in the Atlantic.\nWhy Does it Matter?\nUnderstanding the Butterfly Effect reminds us that our actions matter. It shows how interconnected everything is. So even small acts of kindness or responsibility can ripple out and make a big difference.\nIn Conclusion\nThe Butterfly Effect teaches us to be mindful of our actions. It shows us that the world is a complex web of connections, where even the smallest change can cause a big impact. So next time you’re wondering if what you do matters, remember the Butterfly Effect.",
    createdAt: "2024-05-22T08:56:49.785Z",
    updatedAt: "2024-05-22T08:56:49.785Z",
    __v: 0,
  },
  {
    _id: "664db351373932f6a08928dd",
    title: "What is the Butterfly Effect: Simple Explanation and Examples",
    imgurl:
      "https://media.licdn.com/dms/image/D4D12AQGlLfH9GjAx9w/article-cover_image-shrink_423_752/0/1714061121713?e=1721865600&v=beta&t=eOTYOxTPku5wysUXbF2eHFRIC_WDOdncUiMniryMcNQ",
    description: "",
    service: "2",
    section: "6",
    body: "What is the Butterfly Effect?\nThe Butterfly Effect is a concept from chaos theory. It suggests that even small actions can have big consequences. It’s like a tiny butterfly flapping its wings, which could eventually cause a tornado on the other side of the world.\nHow Does it Work?\nImagine you decide to water a plant one day. Seems simple, right? But think about it. By watering the plant, you’re changing the environment around it. The soil gets moist, which helps the plant grow. As the plant grows, it provides oxygen, affecting the air around it. Birds might come to perch on it, spreading seeds to new places. And on and on it goes.\nExamples of the Butterfly Effect:\nTraffic Jams: You’re driving and you decide to take a different route. That tiny decision might lead to you avoiding a big traffic jam.\nSocial Media: You share a post, and it gets shared by your friends, then by their friends, and so on. Soon, it’s viral!\nWeather Patterns: A butterfly flaps its wings in Brazil, and weeks later, it’s part of the chain reaction that leads to a storm in the Atlantic.\nWhy Does it Matter?\nUnderstanding the Butterfly Effect reminds us that our actions matter. It shows how interconnected everything is. So even small acts of kindness or responsibility can ripple out and make a big difference.\nIn Conclusion\nThe Butterfly Effect teaches us to be mindful of our actions. It shows us that the world is a complex web of connections, where even the smallest change can cause a big impact. So next time you’re wondering if what you do matters, remember the Butterfly Effect.",
    createdAt: "2024-05-22T08:56:49.785Z",
    updatedAt: "2024-05-22T08:56:49.785Z",
    __v: 0,
  },
  {
    _id: "664db351373932f6a08928dd",
    title: "What is the Butterfly Effect: Simple Explanation and Examples",
    imgurl:
      "https://media.licdn.com/dms/image/D4D12AQGlLfH9GjAx9w/article-cover_image-shrink_423_752/0/1714061121713?e=1721865600&v=beta&t=eOTYOxTPku5wysUXbF2eHFRIC_WDOdncUiMniryMcNQ",
    description: "",
    service: "2",
    section: "6",
    body: "What is the Butterfly Effect?\nThe Butterfly Effect is a concept from chaos theory. It suggests that even small actions can have big consequences. It’s like a tiny butterfly flapping its wings, which could eventually cause a tornado on the other side of the world.\nHow Does it Work?\nImagine you decide to water a plant one day. Seems simple, right? But think about it. By watering the plant, you’re changing the environment around it. The soil gets moist, which helps the plant grow. As the plant grows, it provides oxygen, affecting the air around it. Birds might come to perch on it, spreading seeds to new places. And on and on it goes.\nExamples of the Butterfly Effect:\nTraffic Jams: You’re driving and you decide to take a different route. That tiny decision might lead to you avoiding a big traffic jam.\nSocial Media: You share a post, and it gets shared by your friends, then by their friends, and so on. Soon, it’s viral!\nWeather Patterns: A butterfly flaps its wings in Brazil, and weeks later, it’s part of the chain reaction that leads to a storm in the Atlantic.\nWhy Does it Matter?\nUnderstanding the Butterfly Effect reminds us that our actions matter. It shows how interconnected everything is. So even small acts of kindness or responsibility can ripple out and make a big difference.\nIn Conclusion\nThe Butterfly Effect teaches us to be mindful of our actions. It shows us that the world is a complex web of connections, where even the smallest change can cause a big impact. So next time you’re wondering if what you do matters, remember the Butterfly Effect.",
    createdAt: "2024-05-22T08:56:49.785Z",
    updatedAt: "2024-05-22T08:56:49.785Z",
    __v: 0,
  },
  {
    _id: "664db351373932f6a08928dd",
    title: "What is the Butterfly Effect: Simple Explanation and Examples",
    imgurl:
      "https://media.licdn.com/dms/image/D4D12AQGlLfH9GjAx9w/article-cover_image-shrink_423_752/0/1714061121713?e=1721865600&v=beta&t=eOTYOxTPku5wysUXbF2eHFRIC_WDOdncUiMniryMcNQ",
    description: "",
    service: "2",
    section: "6",
    body: "What is the Butterfly Effect?\nThe Butterfly Effect is a concept from chaos theory. It suggests that even small actions can have big consequences. It’s like a tiny butterfly flapping its wings, which could eventually cause a tornado on the other side of the world.\nHow Does it Work?\nImagine you decide to water a plant one day. Seems simple, right? But think about it. By watering the plant, you’re changing the environment around it. The soil gets moist, which helps the plant grow. As the plant grows, it provides oxygen, affecting the air around it. Birds might come to perch on it, spreading seeds to new places. And on and on it goes.\nExamples of the Butterfly Effect:\nTraffic Jams: You’re driving and you decide to take a different route. That tiny decision might lead to you avoiding a big traffic jam.\nSocial Media: You share a post, and it gets shared by your friends, then by their friends, and so on. Soon, it’s viral!\nWeather Patterns: A butterfly flaps its wings in Brazil, and weeks later, it’s part of the chain reaction that leads to a storm in the Atlantic.\nWhy Does it Matter?\nUnderstanding the Butterfly Effect reminds us that our actions matter. It shows how interconnected everything is. So even small acts of kindness or responsibility can ripple out and make a big difference.\nIn Conclusion\nThe Butterfly Effect teaches us to be mindful of our actions. It shows us that the world is a complex web of connections, where even the smallest change can cause a big impact. So next time you’re wondering if what you do matters, remember the Butterfly Effect.",
    createdAt: "2024-05-22T08:56:49.785Z",
    updatedAt: "2024-05-22T08:56:49.785Z",
    __v: 0,
  },
  {
    _id: "664db351373932f6a08928dd",
    title: "What is the Butterfly Effect: Simple Explanation and Examples",
    imgurl:
      "https://media.licdn.com/dms/image/D4D12AQGlLfH9GjAx9w/article-cover_image-shrink_423_752/0/1714061121713?e=1721865600&v=beta&t=eOTYOxTPku5wysUXbF2eHFRIC_WDOdncUiMniryMcNQ",
    description: "",
    service: "2",
    section: "6",
    body: "What is the Butterfly Effect?\nThe Butterfly Effect is a concept from chaos theory. It suggests that even small actions can have big consequences. It’s like a tiny butterfly flapping its wings, which could eventually cause a tornado on the other side of the world.\nHow Does it Work?\nImagine you decide to water a plant one day. Seems simple, right? But think about it. By watering the plant, you’re changing the environment around it. The soil gets moist, which helps the plant grow. As the plant grows, it provides oxygen, affecting the air around it. Birds might come to perch on it, spreading seeds to new places. And on and on it goes.\nExamples of the Butterfly Effect:\nTraffic Jams: You’re driving and you decide to take a different route. That tiny decision might lead to you avoiding a big traffic jam.\nSocial Media: You share a post, and it gets shared by your friends, then by their friends, and so on. Soon, it’s viral!\nWeather Patterns: A butterfly flaps its wings in Brazil, and weeks later, it’s part of the chain reaction that leads to a storm in the Atlantic.\nWhy Does it Matter?\nUnderstanding the Butterfly Effect reminds us that our actions matter. It shows how interconnected everything is. So even small acts of kindness or responsibility can ripple out and make a big difference.\nIn Conclusion\nThe Butterfly Effect teaches us to be mindful of our actions. It shows us that the world is a complex web of connections, where even the smallest change can cause a big impact. So next time you’re wondering if what you do matters, remember the Butterfly Effect.",
    createdAt: "2024-05-22T08:56:49.785Z",
    updatedAt: "2024-05-22T08:56:49.785Z",
    __v: 0,
  },
  {
    _id: "664db351373932f6a08928dd",
    title: "What is the Butterfly Effect: Simple Explanation and Examples",
    imgurl:
      "https://media.licdn.com/dms/image/D4D12AQGlLfH9GjAx9w/article-cover_image-shrink_423_752/0/1714061121713?e=1721865600&v=beta&t=eOTYOxTPku5wysUXbF2eHFRIC_WDOdncUiMniryMcNQ",
    description: "",
    service: "2",
    section: "9",
    body: "What is the Butterfly Effect?\nThe Butterfly Effect is a concept from chaos theory. It suggests that even small actions can have big consequences. It’s like a tiny butterfly flapping its wings, which could eventually cause a tornado on the other side of the world.\nHow Does it Work?\nImagine you decide to water a plant one day. Seems simple, right? But think about it. By watering the plant, you’re changing the environment around it. The soil gets moist, which helps the plant grow. As the plant grows, it provides oxygen, affecting the air around it. Birds might come to perch on it, spreading seeds to new places. And on and on it goes.\nExamples of the Butterfly Effect:\nTraffic Jams: You’re driving and you decide to take a different route. That tiny decision might lead to you avoiding a big traffic jam.\nSocial Media: You share a post, and it gets shared by your friends, then by their friends, and so on. Soon, it’s viral!\nWeather Patterns: A butterfly flaps its wings in Brazil, and weeks later, it’s part of the chain reaction that leads to a storm in the Atlantic.\nWhy Does it Matter?\nUnderstanding the Butterfly Effect reminds us that our actions matter. It shows how interconnected everything is. So even small acts of kindness or responsibility can ripple out and make a big difference.\nIn Conclusion\nThe Butterfly Effect teaches us to be mindful of our actions. It shows us that the world is a complex web of connections, where even the smallest change can cause a big impact. So next time you’re wondering if what you do matters, remember the Butterfly Effect.",
    createdAt: "2024-05-22T08:56:49.785Z",
    updatedAt: "2024-05-22T08:56:49.785Z",
    __v: 0,
  },
];

export default CashData;
