import { PostsCashType } from "../types/DataTypes";

const PostsCash: PostsCashType[] = [
  {
    _id: "1",
    title: "پرچم هزارستان",
    imgurl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Flag_of_Hazaristan.svg/500px-Flag_of_Hazaristan.svg.png",
    body: '<p>The <strong>Flag of Hazaristan</strong> (<a target="_blank" rel="noopener noreferrer nofollow" href="https://en.wikipedia.org/wiki/Dari">Dari</a>&nbsp;: پرچم <strong>هزارستان </strong>) is the <a target="_blank" rel="noopener noreferrer nofollow" href="https://en.wikipedia.org/wiki/National_flag">national flag</a> of <a target="_blank" rel="noopener noreferrer nofollow" class="mw-redirect" href="https://en.wikipedia.org/wiki/Hazaristan">Hazaristan</a> and <a target="_blank" rel="noopener noreferrer nofollow" href="https://en.wikipedia.org/wiki/Hazaras">Hazaras</a>. It was originally proposed by <a target="_blank" rel="noopener noreferrer nofollow" href="https://en.wikipedia.org/wiki/Kamran_Mir_Hazar">Kamran Mir Hazar</a> on <a target="_blank" rel="noopener noreferrer nofollow" href="https://en.wikipedia.org/wiki/Kabul_Press">Kabul Press</a> in 2013...</p>',
    createdAt: "2024-05-22T08:56:49.785Z",
    updatedAt: "2024-05-22T08:56:49.785Z",
    __v: 0,
  },
  {
    _id: "2",
    title: "فرهنگ هزاره‌ها",
    imgurl: "https://images.unsplash.com/photo-1511895426328-dc8714191300?w=500&h=300&fit=crop",
    body: '<p>هزاره‌ها یکی از اقوام اصلی افغانستان با فرهنگی غنی و تاریخ کهن هستند. فرهنگ هزاره‌ها ترکیبی از عناصر فارسی، مغولی و بومی را در بر می‌گیرد. موسیقی، رقص، غذاهای محلی و صنایع دستی از ویژگی‌های بارز این فرهنگ است.</p><p>زبان اصلی هزاره‌ها دری با گویش خاص هزارگی است. همچنین بسیاری از هزاره‌ها به زبان اردو، انگلیسی و سایر زبان‌ها مسلط هستند.</p>',
    createdAt: "2024-05-20T10:30:15.123Z",
    updatedAt: "2024-05-21T14:20:30.456Z",
    __v: 0,
  },
  {
    _id: "3",
    title: "تاریخ هزارستان",
    imgurl: "https://images.unsplash.com/photo-1528181304800-259b08848526?w=500&h=300&fit=crop",
    body: '<p>هزارستان منطقه‌ای تاریخی در مرکز افغانستان است که از دوران باستان محل سکونت هزاره‌ها بوده است. این منطقه در متون تاریخی مختلف از جمله بابرنامه مورد اشاره قرار گرفته است.</p><h2>دوره‌های تاریخی</h2><p>تاریخ هزارستان را می‌توان به چند دوره تقسیم کرد: دوره پیش از اسلام، دوره اسلامی، دوره امپراتوری مغول، و دوره معاصر.</p>',
    createdAt: "2024-05-18T09:15:22.789Z",
    updatedAt: "2024-05-19T11:45:33.101Z",
    __v: 0,
  },
  {
    _id: "4",
    title: "جغرافیای هزارستان",
    imgurl: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=500&h=300&fit=crop",
    body: '<p>هزارستان منطقه‌ای کوهستانی در قلب افغانستان است که در رشته کوه هندوکش قرار دارد. این منطقه از استان‌های بامیان، دایکندی، بخش‌هایی از غور، ارزگان، غزنی و میدان وردک تشکیل شده است.</p><p>بلندترین قله‌های منطقه شامل کوه‌های بابا و شاه‌فولادی است. رودخانه‌های مهم این منطقه شامل هلمند، هریرود و مرغاب می‌شود.</p>',
    createdAt: "2024-05-15T12:45:10.234Z",
    updatedAt: "2024-05-16T16:30:45.678Z",
    __v: 0,
  },
  {
    _id: "5",
    title: "صنایع دستی هزاره‌ها",
    imgurl: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=500&h=300&fit=crop",
    body: '<p>صنایع دستی هزاره‌ها از شهرت جهانی برخوردار است. قالی‌بافی، گلیم‌بافی، سوزندوزی و سفال‌گری از مهم‌ترین صنایع دستی این قوم است.</p><p>طرح‌ها و نقش‌های استفاده شده در صنایع دستی هزاره‌ها معمولاً الهام‌گرفته از طبیعت، زندگی روزمره و باورهای فرهنگی است. رنگ‌های شاد و زنده از ویژگی‌های بارز این آثار هنری است.</p>',
    createdAt: "2024-05-10T08:20:55.901Z",
    updatedAt: "2024-05-12T10:15:40.112Z",
    __v: 0,
  },
  {
    _id: "6",
    title: "غذاهای سنتی هزارگی",
    imgurl: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=500&h=300&fit=crop",
    body: '<p>غذاهای هزارگی ترکیبی از ذائقه‌های مختلف و مواد اولیه محلی است. از معروف‌ترین غذاهای سنتی می‌توان به موارد زیر اشاره کرد:</p><ul><li>دلمه هزارگی</li><li>آش هزارگی</li><li>کله‌پاچه</li><li>نان‌های محلی</li><li>شیرینی‌های سنتی</li></ul><p>این غذاها معمولاً در مراسم‌های خاص و مهمانی‌ها تهیه می‌شوند.</p>',
    createdAt: "2024-05-05T14:10:33.445Z",
    updatedAt: "2024-05-08T09:25:50.334Z",
    __v: 0,
  },
  {
    _id: "7",
    title: "موسیقی و رقص محلی",
    imgurl: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=500&h=300&fit=crop",
    body: '<p>موسیقی هزارگی دارای ریتم‌های خاص و سازهای محلی منحصر به فرد است. دایره، رباب، و سازهای کوبه‌ای از مهم‌ترین سازهای این موسیقی هستند.</p><p>رقص‌های محلی هزاره‌ها معمولاً گروهی اجرا می‌شوند و حرکات هماهنگ و ریتمیک دارند. این رقص‌ها در عروسی‌ها و جشن‌های محلی اجرا می‌شوند.</p>',
    createdAt: "2024-05-01T11:30:20.667Z",
    updatedAt: "2024-05-03T13:40:15.889Z",
    __v: 0,
  },
  {
    _id: "8",
    title: "معماری سنتی",
    imgurl: "https://images.unsplash.com/photo-1548013146-72479768bada?w=500&h=300&fit=crop",
    body: '<p>معماری سنتی هزارستان تحت تأثیر شرایط جغرافیایی و آب و هوایی منطقه شکل گرفته است. خانه‌های گلی، قلعه‌های تاریخی و مساجد قدیمی از نمونه‌های بارز این معماری هستند.</p><p>بامیان با مجسمه‌های بودا و غارهای تاریخی‌اش یکی از مهم‌ترین مراکز معماری تاریخی در منطقه هزارستان است.</p>',
    createdAt: "2024-04-28T16:45:10.112Z",
    updatedAt: "2024-04-30T10:20:30.556Z",
    __v: 0,
  },
  {
    _id: "9",
    title: "پوشش سنتی",
    imgurl: "https://images.unsplash.com/photo-1523381210434-271e8be1f52b?w=500&h=300&fit=crop",
    body: '<p>پوشش سنتی هزاره‌ها برای مردان و زنان متفاوت است. مردان معمولاً لباس‌های گشاد و کلاه‌های پشمی می‌پوشند در حالی که زنان از لباس‌های رنگارنگ با سوزندوزی‌های زیبا استفاده می‌کنند.</p><p>این پوشش‌ها نه تنها جنبه زیبایی بلکه نشان‌دهنده هویت فرهنگی و منطقه‌ای افراد است.</p>',
    createdAt: "2024-04-25T09:15:40.778Z",
    updatedAt: "2024-04-27T14:30:25.990Z",
    __v: 0,
  },
  {
    _id: "10",
    title: "جشن‌ها و مراسم",
    imgurl: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=500&h=300&fit=crop",
    body: '<p>هزاره‌ها مانند دیگر اقوام افغانستان جشن‌ها و مراسم مختلفی دارند. نوروز، عید فطر، عید قربان و مراسم عروسی از مهم‌ترین این مراسم هستند.</p><p>هر کدام از این مراسم آداب و رسوم خاص خود را دارند و معمولاً با غذاهای خاص، موسیقی و رقص همراه هستند.</p>',
    createdAt: "2024-04-20T13:20:55.123Z",
    updatedAt: "2024-04-22T08:45:10.456Z",
    __v: 0,
  }
];

export default PostsCash;